In [23]:
import numpy as np
import pandas as pd

In [24]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [25]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
cv=CountVectorizer(ngram_range=(1, 2))

In [33]:
bow=cv.fit_transform(df['text'])

In [36]:
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}
11


In [30]:
print(bow[0].toarray())

print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [31]:
cv.transform(["campusx watch and of hello campusx comments"]).toarray()

array([[2, 0, 0, 1, 0]], dtype=int64)