In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('dataset/IMDB Dataset.csv')

In [3]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [5]:
df['review'][0].lower()

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fa

In [7]:
df=df['review'].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [8]:
import re

In [9]:
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    
    return pattern.sub(r'',text)

In [13]:
df['review'].apply(remove_html_tags)

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...                        
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [15]:
def remove_urls(text):
    # This regular expression matches URLs
    url_pattern = re.compile(r'https?://\S+|www\.\S+')

    # Replace URLs with an empty string
    clean_text = re.sub(url_pattern, '', text)
    return clean_text

In [17]:
df=df['review'].apply(remove_html_tags)

In [18]:
df

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...                        
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [1]:
import nltk

In [2]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [3]:
text = "Tokenization is an important step in NLP. It breaks down text into smaller units, such as words or subwords."

In [4]:
tokens = word_tokenize(text)

In [5]:
print("Original text:", text)
print("Tokens:", tokens)

Original text: Tokenization is an important step in NLP. It breaks down text into smaller units, such as words or subwords.
Tokens: ['Tokenization', 'is', 'an', 'important', 'step', 'in', 'NLP', '.', 'It', 'breaks', 'down', 'text', 'into', 'smaller', 'units', ',', 'such', 'as', 'words', 'or', 'subwords', '.']


In [6]:
sent=sent_tokenize(text)

In [7]:
sent

['Tokenization is an important step in NLP.',
 'It breaks down text into smaller units, such as words or subwords.']

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

# Sample documents
documents = [
    'This is the first document this first also did.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
    'first is a stopword'
]

# Create an instance of CountVectorizer
vectorizer = CountVectorizer(max_features=5,binary=True)

# Learn the vocabulary and transform the documents into a document-term matrix
X = vectorizer.fit_transform(documents)

# Print the vocabulary (unique words)
print("Vocabulary:")
print(vectorizer.get_feature_names_out())

# Print the document-term matrix (sparse matrix)
print("Document-Term Matrix:")
print(X.toarray())


Vocabulary:
['document' 'first' 'is' 'the' 'this']
Document-Term Matrix:
[[1 1 1 1 1]
 [1 0 1 1 1]
 [0 0 1 1 1]
 [1 1 1 1 1]
 [0 1 1 0 0]]
