In [1]:
import numpy as np
import pandas as pd

In [2]:
temp_df = pd.read_csv("dataset\IMDB Dataset.csv")

In [3]:
df = temp_df.iloc[:10000]

In [4]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.shape

(10000, 2)

In [55]:
text=df['review'][999]

In [7]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df.duplicated().sum()

17

In [10]:
df.drop_duplicates(inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_21664\3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [11]:
df.duplicated().sum()

0

In [12]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [13]:
df['review'] = df['review'].apply(remove_tags)

C:\Users\hp\AppData\Local\Temp\ipykernel_21664\2336150696.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [56]:
df['sentiment'][5333]

'positive'

In [15]:
df['review'] = df['review'].apply(lambda x:x.lower())

C:\Users\hp\AppData\Local\Temp\ipykernel_21664\740760900.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [16]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

C:\Users\hp\AppData\Local\Temp\ipykernel_21664\2826946130.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [17]:
df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [18]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [19]:
X

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [20]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [21]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [22]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [24]:
X_train.shape

(7986, 1)

In [43]:
X_test['review'][5333]

'8 simple rules dating teenage daughter auspicious start. supremely-talented tom shadyac involved project. meant comedy would nothing less spectacular, that\'s exactly happened: show remains one freshest, funniest, wittiest shows made long time. every line, facial expression, casting choice, scene, wreaked perfection. one episode thought, "man good rest". one standout. again, kind perfectionism we\'ve come expect tom. know, tom shadyac director ace ventura (first movie), nutty professor (first one) liar liar. quite résumé. he\'s producer director, magic touch felt every episode.the family consists of:the father: paul hennessy (john ritter): nice, slightly neurotic, pushover time time, works sports writer. john unfortunately passed away 2003 leaving fond memory near-sure cancellation contemplations suits.the mother: cate (katey sagal): come on, fall love katey played peg married children? al bundy hero. viewers gave respect love never had. without peg\'s nonchalant, parasitic, lazy life

In [25]:
# Applying BoW
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
cv = CountVectorizer()

In [27]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [28]:
X_train_bow.shape

(7986, 48282)

In [29]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [30]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6324486730095142

In [31]:
confusion_matrix(y_test,y_pred)

array([[717, 235],
       [499, 546]], dtype=int64)

In [32]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8442663995993991

In [34]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8412618928392589

## Using TfIdf

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [36]:
tfidf = TfidfVectorizer()

In [37]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [38]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8487731597396094

In [44]:
text=X_test['review'][5333]

In [46]:
test = tfidf.transform([text])

In [47]:
rf.predict(test)

array([1])

In [8]:
import gensim

In [9]:
from gensim.models import Word2Vec,KeyedVectors

In [39]:
!pip install wget


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import urllib.request

url = "https://nlp.stanford.edu/data/glove.6B.zip"
filename = "glove.6B.zip"

urllib.request.urlretrieve(url, filename)

In [ ]:
import zipfile

zip_file = 'glove.6B.zip'
extract_dir = '/glove/'

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)


In [ ]:
glove_file = '/glove/glove.6B.100d.txt'

In [ ]:
glove_file

In [43]:
from gensim.scripts.glove2word2vec import glove2word2vec

# Convert GloVe format to Word2Vec format
word2vec_output_file = '/glove/glove.6B.100d.word2vec'
glove_file = '/glove/glove.6B.100d.txt'

glove2word2vec(glove_file, word2vec_output_file)

C:\Users\hp\AppData\Local\Temp\ipykernel_1260\3572906459.py:7: DeprecationWarning: Call to deprecated `glove2word2vec` (KeyedVectors.load_word2vec_format(.., binary=False, no_header=True) loads GLoVE text vectors.).
  glove2word2vec(glove_file, word2vec_output_file)


(400000, 100)

In [44]:
# Load the Word2Vec model
from gensim.models import KeyedVectors
model = KeyedVectors.load_word2vec_format(word2vec_output_file, binary=False)

In [45]:
model['cricket'].shape

(100,)

In [46]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

In [47]:
sw_list

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [48]:
# Remove stopwords

X_train = X_train['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))
# Remove stopwords

X_test = X_test['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [49]:
import spacy
import en_core_web_sm
# Load the spacy model. This takes a few seconds.
nlp = en_core_web_sm.load()
# Process a sentence using the model
doc = nlp(X_train.values[0])
print(doc.vector)

[-9.38924626e-02 -3.84084344e-01  5.38174808e-02 -5.68839815e-03
  5.53607009e-02  4.34335917e-01  1.12127282e-01  3.69744062e-01
  2.90832311e-01 -1.70808136e-01  2.64332980e-01 -1.62290543e-01
 -3.06538224e-01 -2.85405099e-01 -1.81089625e-01  1.67842567e-01
 -5.53924069e-02 -2.39561155e-01 -9.84708741e-02 -2.47755840e-01
 -1.03777826e-01  3.14559907e-01 -1.58189446e-01  9.29157138e-02
 -6.30339906e-02  1.74012944e-01  2.98766553e-01  6.10951722e-01
  2.79511511e-01  6.51886985e-02 -5.98237105e-02 -1.00067459e-01
  2.43561059e-01 -5.19757196e-02  1.00620603e-02 -1.06087245e-01
  2.54588515e-01 -9.97592583e-02 -1.51748762e-01 -2.58460432e-01
 -3.79791379e-01  1.97484657e-01 -5.39284982e-02  4.59246263e-02
 -4.72242162e-02 -1.32725611e-01  2.24066466e-01 -1.11504689e-01
  2.12011918e-01  1.45252958e-01 -3.38403374e-01  1.08032361e-01
  7.14340210e-02 -1.43950149e-01 -4.83557396e-02  7.11817760e-03
  2.28908435e-01 -6.45604953e-02  1.57704279e-02 -2.28218064e-02
  8.61754715e-02 -1.64328

In [50]:
!pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz


  ERROR: HTTP error 404 while getting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz
ERROR: Could not install requirement https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz because of HTTP error 404 Client Error: Not Found for url: https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz for URL https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [51]:
!python -m spacy download en_core_web_sm

     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.1/12.8 MB 1.6 MB/s eta 0:00:08
     ---------------------------------------- 0.1/12.8 MB 1.4 MB/s eta 0:00:09
      --------------------------------------- 0.2/12.8 MB 1.7 MB/s eta 0:00:08
     - -------------------------------------- 0.3/12.8 MB 1.8 MB/s eta 0:00:07
     - -------------------------------------- 0.4/12.8 MB 1.9 MB/s eta 0:00:07
     - -------------------------------------- 0.6/12.8 MB 2.0 MB/s eta 0:00:07
     -- ------------------------------------- 0.7/12.8 MB 2.3 MB/s eta 0:00:06
     -- ------------------------------------- 0.8/12.8 MB 2.3 MB/s eta 0:00:06
     --- ------------------------------------ 1.0/12.8 MB 2.5 MB/s eta 0:00:05
     --- ------------------------------------ 1.1/12.8 MB 2.4 MB/s eta 0:00:05
     ---- ----------------------------------- 1.3/12.8 MB 2.7 MB/s eta 0:00:05
     ---- ----------------------------------- 1.4/12.8 MB 2


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [52]:
input_arr = []
for item in X_train.values:
    doc = nlp(item)
    input_arr.append(doc.vector)

In [53]:
input_arr = np.array(input_arr)

In [54]:
input_arr.shape

(7986, 96)

In [55]:
input_test_arr = []
for item in X_test.values:
    doc = nlp(item)
    input_test_arr.append(doc.vector)

In [56]:
input_test_arr = np.array(input_test_arr)

In [57]:
input_test_arr.shape

(1997, 96)

In [58]:
from sklearn.naive_bayes import GaussianNB

In [59]:
gnb = GaussianNB()
gnb.fit(input_arr,y_train)

GaussianNB()

In [60]:
y_pred = gnb.predict(input_test_arr)
accuracy_score(y_test,y_pred)

0.6169253880821232